version: '3.8'
services:
  alekhin:
    image: alekhin:latest
    container_name: alekhin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - ./config:/app/config
      - ./db.sqlite3:/app/db.sqlite3
