version: '3.8'
services:
  checker:
    image: checker:latest
    container_name: checker
    build:
      context: ./checker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./media:/app/media
      - ./config:/app/config
      - ./db.sqlite3:/app/db.sqlite3
